import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap-grid.min.css";
import "bootstrap/dist/css/bootstrap-utilities.min.css";
// import "primereact/resources/themes/lara-dark-blue/theme.css";
import "primereact/resources/themes/vela-blue/theme.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "React Buttons",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="container">{children}</div>
            </body>
        </html>
    );
}
