import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./page.css";
import "tailwindcss/tailwind.css";
import Navigation from "@/components/navigation/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "React Buttons",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} main`}>
                <main>
                    <Navigation />
                    {children}
                </main>
            </body>
        </html>
    );
}
